### ISSUE TITLE
I get a "fatal: Failed to recurse into submodule path 'middleware'"

### ISSUE THREAD

**Issue by stevns** [scpcom/LicheeSG-Nano-Build#1]
Hello All,

When cloning the repo i get the following error:

`remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Enumerating objects: 19931, done.
remote: Counting objects: 100% (19929/19929), done.
remote: Compressing objects: 100% (11250/11250), done.
remote: Total 13537 (delta 6470), reused 5438 (delta 2018), pack-reused 0 (from 0)
Receiving objects: 100% (13537/13537), 11.35 MiB | 5.10 MiB/s, done.
Resolving deltas: 100% (6470/6470), completed with 4927 local objects.
From https://github.com/scpcom/u-boot
 * branch              f4fd67bfa618386fe465ef164c92c3ad5e0600fe -> FETCH_HEAD
Submodule path 'u-boot-2021.10': checked out 'f4fd67bfa618386fe465ef164c92c3ad5e0600fe'
fatal: Failed to recurse into submodule path 'middleware'
stevns@nanokvm-builder:~/LicheeSG-Nano-Build$
`

Anyone else getting this?

Thanks :-)

/stevns

**Comment by scpcom** [comment]
Maybe you cloned while I was pushing the updates.
Does it work now?

**Comment by stevns** [comment]
Now i get this error:

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:scpcom/ireader-avcodec.git' into submodule path '/home/stevns/LicheeSG-Nano-Build/middleware/sample/test_mmf/media_server-1.0.x/avcodec' failed
Failed to clone 'avcodec' a second time, aborting
fatal: Failed to recurse into submodule path 'middleware/sample/test_mmf/media_server-1.0.x'
fatal: Failed to recurse into submodule path 'middleware'
stevns@nanokvm-builder:~/LicheeSG-Nano-Build$

**Comment by scpcom** [comment]
I never changed "github.com:scpcom/ireader-avcodec".
Maybe you have connectivity problems?

**Comment by krystophv** [comment]
Some of the submodules are specified with the SSH git clone syntax: `git@github.com...` instead of the HTTP syntax. You need to ensure that you can use the SSH syntax in whatever environment you're trying to run the build in (which will involve having an SSH key set up and properly associated with your GitHub account).

**Comment by scpcom** [comment]
Thanks for the hint. I changed the urls to https now.

**Comment by stevns** [comment]
Works :-)Sent from my iPhoneOn 23 Nov 2024, at 18.57, scpcom ***@***.***> wrote:﻿
Thanks for the hint. I changed the urls to https now.
