### ISSUE TITLE
Additional packages required on Ubuntu 24.04 (Distrobox)

### ISSUE THREAD

**Issue by argus-core** [scpcom/LicheeSG-Nano-Build#2]
I needed to install the following packages to complete a build on a fresh install of Ubuntu 24.04 in Distrobox:

- cpio
- xxd
- ~~python3-jinja2~~ already done in c41dc264f9980f35645d65f377c2ece4fd0397db

Should those be added to prepare-host.sh?

**Comment by scpcom** [comment]
Thank you for reporting. I am testing it with a fresh setup of ubuntu server minimal sometimes, which does seem to have cpio and xxd already installed.
I will add them to prepare-host.sh to make sure it works on the distrobox variant.

**Comment by scpcom** [comment]
Done: https://github.com/scpcom/LicheeSG-Nano-Build/commit/8ab921895333ca8b2d30b8006959709207346579
