### ISSUE TITLE
Is libcvikernel.so really need to be installed as prebuilt? 

### ISSUE THREAD

**Issue by legath** [scpcom/LicheeSG-Nano-Build#4]
libcvikernel.so can be build from sopgho repos, may be additional logic present in tpu-demo package? 
Please explain the idea

**Comment by scpcom** [comment]
I do not know libcvikernel.so can you give me hint where to find it?
I could not find any source code for tpudemo, this is the reason I disabled it in the build-nanokvm script.

**Comment by legath** [comment]
i can make PR for libcvi kernel, i made patches for sipeed repo, found your repo too late, i will remake it

**Comment by legath** [comment]
not needed because supported by maix-cdk
